### ISSUE TITLE
Multi Character variable

### ISSUE THREAD

**Issue by jincejames** [augustt198/latex2sympy#21]
How can we use a multi character variable
in latex suntax we use \mathit, and its not yet supported 

Is this the only way??
 process_sympy("{\\frac {\\OperationHours}{\\TotalPossibleOperationHours}} \\times \\Mech 100")

**Comment by hermanbergwerf** [comment]
Same issue for me

**Comment by augustt198** [comment]
Interesting, I didn't know that existed in latex. I've implemented it in this commit: https://github.com/augustt198/latex2sympy/commit/0e42864cad97666eda0f842d2488974ac85f7998
