### ISSUE TITLE
Add python version to README

### ISSUE THREAD

**Issue by Mar4eli** [augustt198/latex2sympy#26]
Hello, thank you for your lib!
Can you please add required python version for your readme. I have had a hard time with python 3.5 and syntax error in lib, python 2.7 (via anaconda) works perfectly.

**Comment by augustt198** [comment]
I've only tested the project using python 2.7. That said, I don't think it would be too hard to run it in python 3.5. I think the only thing that would have to be updated is the antlr4 dependency (using antlr4-python3-runtime instead of antlr4-python2-runtime)

**Comment by LennyLip** [comment]
I've been installed latex2sympy with python 3 and have only 83/162 STRINGS tests PASSED .  
Can anybody else confirm it?
