### ISSUE TITLE
Can't parse expr like "2x"

### ISSUE THREAD

**Issue by shuokay** [augustt198/latex2sympy#3]
```2x``` in latex format should be convert to ```2*x``` in sympy format, however, latex2sympy converted it to ```2 x```

**Comment by The-Penultimate-Defenestrator** [comment]
Yeah, but SymPy can process this from the string (`implicit_multiplication_application`)

**Comment by augustt198** [comment]
Fixed in `obj` branch:

```py
>>> process_sympy("2x")
2*x
```
